/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_ASYM_KEYS_T_H
#define EDGER8R_ASYM_KEYS_T_H

#include <openenclave/enclave.h>

#include "asym_keys_args.h"

OE_EXTERNC_BEGIN

/**** Trusted function IDs ****/
enum
{
    asym_keys_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** ECALL marshalling structs. ****/
/**** ECALL prototypes. ****/

/**** Untrusted function IDs. ****/
enum
{
    asym_keys_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

/**** OCALL marshalling structs. ****/
/**** OCALL prototypes. ****/

OE_EXTERNC_END

#endif // EDGER8R_ASYM_KEYS_T_H
