/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_ASYM_KEYS_U_H
#define EDGER8R_ASYM_KEYS_U_H

#include <openenclave/host.h>

#include "asym_keys_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_asym_keys_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
    const oe_enclave_setting_t* settings,
    uint32_t setting_count,
    oe_enclave_t** enclave);

/**** Trusted function IDs ****/
enum
{
    asym_keys_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** ECALL marshalling structs. ****/
/**** ECALL prototypes. ****/

/**** Untrusted function IDs. ****/
enum
{
    asym_keys_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

/**** OCALL marshalling structs. ****/
/**** OCALL prototypes. ****/

OE_EXTERNC_END

#endif // EDGER8R_ASYM_KEYS_U_H
